// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
...ffffff..........ccc..
...ff22ccff.......c44f..
....fffccccfff...c442f..
....cc24442222ccc4422f..
...c99b222222222cc22fc..
..c999111b222222222222c.
.c2bb11199222ccccccc222f
c22222222222c222cccfffff
f22222222222442222ccc...
.f222222222224442222c...
..ff2222222cffc44222c...
....fffffffcffffcccc....
.........f2c2ffff.......
.........fcc2ffff.......
..........ffffff........
........................
`;
            case "image2":
            case "shark2":return img`
..............cfff..............
............ccddbf..............
...........cbddbff.........ccc..
..........fccbbcf.........cbbc..
...fffffffccccccff.......cdbc...
.ffcbbbbbbbbbbbbbcfff....cdbf...
fcbbbbbbbbbcbbbbbbcccff.cdbf....
fbcbbbbffbbbcbcbbbcccccffdcf....
fbb1111ffbbbcbcbbbccccccbbcf....
.fb11111111bbcbbbccccccccbbcf...
..fccc33cb11bbbbcccccccfffbbf...
...fc131c111bbbcccccbdbc..fbbf..
....f33c111cbbccdddddbc....fff..
.....ff1111fdbbccddbcc..........
.......cccccfdbbbfcc............
.............fffff..............
`;
            case "image3":
            case "shark0":return img`
..............cfff..............
............ccddbf..............
...........cbddbff.........ccc..
..........fccbbcf.........cbbc..
...fffffffccccccff.......cdbc...
.ffcbbbbbbbbbbbbbcfff....cdbf...
fcbbbbbbbbbcbbbbbbcccff.cdbf....
fbcbbbbffbbbcbcbbbcccccffdcf....
fbb1111ffbbbcbcbbbccccccbbcf....
.fb11111111bbcbbbccccccccbbcf...
..fccc33cb11bbbbcccccccfffbbf...
...fc131c111bbbcccccbdbc..fbbf..
....f33c111cbbccdddddbc....fff..
.....ff1111fdbbccddbcc..........
.......cccccfdbbbfcc............
.............fffff..............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
